# -*- coding: utf-8 -*-
"""CURSO 2021 - primeiro exercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D4KLAjtVMHGQhWJQYhBbu8QQ3H91QMm2
"""

print("Olá mundo")

print("Estou começando com python")

"""Vamos pegar e imprimir o texto de uma variável"""

nome = "Guto Xavier"
print(nome)