# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bYGoifl5ZlDMTXQj2QwbYp5NAXvIwYKV
"""

print('ola')