# -*- coding: utf-8 -*-
"""CURSO 2021 02 - VARIAVEIS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yxXcJYFCxicIojW-68mNMyq401nHQrix
"""

print('OLÁ')
# PRINT é diferente de Print que é diferente de print

# print('10+2=')
# print(10+2)
# concatenação --> junção de duas informações ( , )
# print('João' , 'Paulo')
print('10+2=' , 10+2)
#adição
print(10+2)

#multiplicação
print(10*2)

#divisão
print(10/2)

#subtração
print(10-2)

# variáveis
# variável --> espaço reservado na memória com um nome
# operador = (igual) --> atribuição, atribuir o que está do lado direito 
# ao elemento que estiver ao lado esquerdo
numero1 = 10
print(numero1)

numero1 = 13
print(numero1)

numero2 = 17
print(numero1 + numero2)

# Entrada de dados
nome = input("Informe seu nome")
diaDeAniversario = input("Qual dia você nasceu?")
print("Olá" , nome)
print("Você nasceu no dia" , diaDeAniversario)

# dar nomes significativos pras variáveis
# diaDeAniversario

# variáveis tem tipos
# - texto --> string
# - numérico --> inteiros ( int ) decimais ( float )
# - booleano --> true (verdadeiro) false (falso)

# operador + --> número = soma , texto = concatenação
# operador * --> número = multiplicação 

valor1 = int(input("Digite um número: "))
valor2 = int(input("Digite outro número: "))
print(valor1 + valor2)